Hello World
Requirement already satisfied: pytest in /usr/local/lib/python3.10/dist-packages (8.3.3)
Requirement already satisfied: einops in /usr/local/lib/python3.10/dist-packages (0.8.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from pytest) (24.2)
Requirement already satisfied: exceptiongroup>=1.0.0rc8 in /usr/local/lib/python3.10/dist-packages (from pytest) (1.2.2)
Requirement already satisfied: iniconfig in /usr/local/lib/python3.10/dist-packages (from pytest) (2.0.0)
Requirement already satisfied: tomli>=1 in /usr/local/lib/python3.10/dist-packages (from pytest) (2.1.0)
Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.10/dist-packages (from pytest) (1.5.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Traceback (most recent call last):
  File "/tmp/telerun-execute/155f9172-d2b3-4ab3-852c-b6c076b4f8e1/fast-hadamard-transform/setup.py", line 22, in <module>
    print(f"{theory_cuda_home = }, {os.path.exists(theory_cuda_home) = }")
  File "/usr/lib/python3.10/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Traceback (most recent call last):
  File "/tmp/telerun-execute/155f9172-d2b3-4ab3-852c-b6c076b4f8e1/fast-hadamard-transform/tests/test_fast_hadamard_transform.py", line 10, in <module>
    from fast_hadamard_transform.fast_hadamard_transform_interface import hadamard_transform, hadamard_transform_ref
ModuleNotFoundError: No module named 'fast_hadamard_transform'
